-- 1. Database మరియు Schema క్రియేషన్
CREATE OR REPLACE DATABASE RETAIL_DWH;
CREATE OR REPLACE SCHEMA RETAIL_DWH.RAW_DATA;

-- 2. Raw Customers Table (STAGING)
CREATE OR REPLACE TABLE RETAIL_DWH.RAW_DATA.STG_CUSTOMERS (
    CUSTOMER_ID INT,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    CITY STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 3. Raw Orders Table (STAGING)
CREATE OR REPLACE TABLE RETAIL_DWH.RAW_DATA.STG_ORDERS (
    ORDER_ID INT,
    CUSTOMER_ID INT,
    ORDER_DATE DATE,
    TOTAL_AMOUNT DECIMAL(10,2),
    STATUS STRING
);

-- 4. Sample Data ఇన్సర్ట్ చేయడం
INSERT INTO RETAIL_DWH.RAW_DATA.STG_CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, CITY)
VALUES 
(101, 'Bharath', 'D', 'bharath@example.com', 'Hyderabad'),
(102, 'John', 'Doe', 'john.doe@example.com', 'Bangalore');

INSERT INTO RETAIL_DWH.RAW_DATA.STG_ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT, STATUS)
VALUES 
(1, 101, '2026-04-01', 5000.00, 'COMPLETED'),
(2, 102, '2026-04-01', 2500.50, 'PENDING');

-- 5. Final Analytics View (Medallion Architecture - Gold Layer)
CREATE OR REPLACE VIEW RETAIL_DWH.RAW_DATA.CUSTOMER_ORDER_SUMMARY AS
SELECT 
    C.CUSTOMER_ID,
    C.FIRST_NAME || ' ' || C.LAST_NAME AS FULL_NAME,
    COUNT(O.ORDER_ID) AS TOTAL_ORDERS,
    SUM(O.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM RETAIL_DWH.RAW_DATA.STG_CUSTOMERS C
LEFT JOIN RETAIL_DWH.RAW_DATA.STG_ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY 1, 2;
